title:             å‡¯éªŠä¸­å›½
email:             your-email@example.com
description:       æ¬¢è¿è®¿é—®Celier China ğŸ‘ğŸ‘ğŸ‘
author:            å‡¯éªŠä¸­å›½
baseurl:           "/"
url:               "https://www.celier-china.com"

# Social Profiles
twitter_username:  SBootstrap
github_username:   xianyuxmu
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
